settings:
  legacy:
    # コンテナの場合レガシーモードでないと動かない
    force: true
    interval: 0s
server:
  status: true
  open: false
  # ホストはコンテナ名で指定
  host: api
  port: 5002
schema:
- name: github.com/birnamwood/go-server-base
  path: .
  commands:
    fmt:
      status: true
      args:
      - -s
      - -w
    install:
      status: true
      method: go build -o server ./cmd/go-server-base/main.go
    run:
      status: true
      method: ./server
  watcher:
    extensions:
    - go
    - yaml
    paths:
    - ./
    ignored_paths:
    - .git
    - .realize
    - vendor
